binop_separator = "Back"
brace_style = "AlwaysNextLine"
color = "Always"
combine_control_expr = false
condense_wildcard_suffixes = true
control_brace_style = "AlwaysNextLine"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hard_tabs = false
hex_literal_case = "Upper"
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
match_block_trailing_comma = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 28
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
